name: Manual Run Silverlake.py

on:
  workflow_dispatch:  # Pozwala na ręczne uruchamianie workflow

permissions:
  contents: write  # Dodanie uprawnień do zapisu

jobs:
  run-lstm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Wybierz odpowiednią wersję Pythona

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Zakładając, że masz plik requirements.txt
        pip install git+https://github.com/statsmodels/statsmodels.git

    - name: Run Silverlake.py 18 times
      run: |
        for i in {1..20}; do
          echo "Run $i"
          python Silverlake.py
        done
        
    - name: Save results
      run: |
        mkdir -p artifacts
        cp _fore_DX.pkl artifacts/
        cp silver_fore.xlsx artifacts/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: artifacts/

    - name: Pull latest changes
      run: git pull origin master
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Commit and push results
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add artifacts/_fore_DX.pkl artifacts/silver_fore.xlsx
        git commit -m 'Add results from Silverlake.py'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Move files
      run: |
        mv artifacts/_fore_DX.pkl .
        mv artifacts/silver_fore.xlsx .
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add _fore_DX.pkl silver_fore.xlsx
        git commit -m 'Move _fore_DX.pkl and silver_fore.xlsx from artifacts to root directory'
        git push origin master  
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
